# Setup
name: KnighTechie.
tagline: Software Engineer - Coding Web.
baseurl: ""
description: Tech Enthusiast.<br/> <span> Trying to contribute back to community.</span><br/> <span>For the Love of Code.</span>
social: [{
  link: "https://github.com/srsandeepkumar",
  which: "GitHub",
  icon: "https://res.cloudinary.com/djgnze1er/image/upload/v1491932773/GitHub_Filled-500_sl3iek.png"
}, {
  link: "https://www.linkedin.com/in/infosandeep/",
  which: "LinkedIn",
  icon: "https://res.cloudinary.com/djgnze1er/image/upload/v1491932786/LinkedIn-528_kul9pm.png"
}, {
  link: "https://twitter.com/SrSandeepKumar",
  which: "Twitter",
  icon: "https://res.cloudinary.com/djgnze1er/image/upload/v1491932768/Twitter-528_iun6md.png"
}, {
  link: "https://www.youtube.com/channel/UC8aSVykuSWwTBX74lQsqyGw",
  which: "YouTube",
  icon: "https://res.cloudinary.com/djgnze1er/image/upload/v1491932765/YouTube_2-528_lyg6av.png"
}]
collections:
  reactjs:
    output: true
    permalink: /:collection/:name
  year2018:
    output: true
    permalink: /:collection/:name
  year2017:
    output: true
    permalink: /:collection/:name

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
